version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/mgr"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/ctl"
    schedule:
      interval: "weekly"
