cut_body_after = "" # don't include text from the PR body in the merge commit message
status = [
  "Evaluate flake.nix",
  "check lightning-kld [x86_64-linux]",
  "check lightning-kld-benches [x86_64-linux]",
  "check lightning-kld-clippy [x86_64-linux]",
  "check treefmt [x86_64-linux]",
  "devShell default [x86_64-linux]",
  "package bitcoind [x86_64-linux]",
  "package cockroachdb [x86_64-linux]",
  "package default [x86_64-linux]",
  "package lightning-kld [x86_64-linux]",
]
