cut_body_after = "" # don't include text from the PR body in the merge commit message
status = [
  "Evaluate flake.nix",
  "check kld [x86_64-linux]",
  "check kld-benches [x86_64-linux]",
  "check kld-clippy [x86_64-linux]",
  "check kld-tests [x86_64-linux]",
  "check treefmt [x86_64-linux]",
  "devShell default [x86_64-linux]",
  "nixosConfig example-cockroach-node",
  "nixosConfig example-kld-node",
  "package bitcoind [x86_64-linux]",
  "package cockroachdb [x86_64-linux]",
  "package default [x86_64-linux]",
  "package kld [x86_64-linux]",
  "package remote-pdb [x86_64-linux]"
]
