[package]
name = "logger"
version = "0.1.0"
edition = "2021"

[dependencies]
lightning = { version = "0.0.112", features = ["max_level_trace"] }
log = { version = "0.4", features = ["std"] }
once_cell = "1.16.0"

[lib]
doctest = false
