[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.66", features = [ "backtrace" ] }
axum = "0.6.1"
bitcoin = "0.29.2"
futures = "0.3"
serde = "1.0"
serde_json = "1.0"
