name: system info checker

concurrency:
  group: system-info-${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Check System Info Update
        run: nix develop -c system-info check
